version: '3'
services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    volumes:
     - ./src:/code
    expose:
      - 8000
  redis:
    image: "redis:alpine"
  nginx:
    restart: always
    image: nginx
    ports:
        - 8000:8000
    volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  